services:
  # Spring Boot Application
  - type: web
    name: dpmhc-backend
    runtime: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      
      # Database (auto-populated from Render PostgreSQL service)
      - key: DATABASE_URL
        fromDatabase:
          name: dpmhc-db
          property: connectionString
      
      # Redis (auto-populated from Render Redis service)
      - key: REDIS_URL
        fromService:
          name: dpmhc-redis
          type: redis
          property: connectionString
      
      # Memory optimization environment variable
      - key: JAVA_TOOL_OPTIONS
        value: "-Xmx384m -Xms100m -XX:+UseG1GC"
      
      # IMPORTANT: Set these manually in Render Dashboard under Environment Variables
      # DO NOT commit sensitive credentials to Git!
      # 
      # Required Environment Variables to Set in Dashboard:
      # - JWT_SECRET: Generate with: openssl rand -base64 32
      # - CLOUDINARY_CLOUD_NAME: Your Cloudinary cloud name
      # - CLOUDINARY_API_KEY: Your Cloudinary API key
      # - CLOUDINARY_API_SECRET: Your Cloudinary API secret
      # - MAIL_USERNAME: Your Gmail address
      # - MAIL_PASSWORD: Your Gmail app password (not regular password)
      # - APP_BASE_URL: Your Render app URL (e.g., https://dpmhc-backend.onrender.com)
    
    healthCheckPath: /actuator/health
    
    # Auto-deploy on push to main branch
    autoDeploy: true
    
    # Build command (optional, Docker handles this)
    # buildCommand: "./mvnw clean package -DskipTests"
    
    # Disk space for logs (minimal for free tier)
    disk:
      name: data
      mountPath: /app/logs
      sizeGB: 1

  # Redis Cache Service
  - type: redis
    name: dpmhc-redis
    plan: free
    region: oregon
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []

# PostgreSQL Database
databases:
  - name: dpmhc-db
    databaseName: dpmhc
    user: dpmhc_user
    plan: free
    region: oregon
    ipAllowList: []