# ===========================================
# RENDER.COM DEPLOYMENT CONFIGURATION
# ===========================================

services:
  # Main Spring Boot Application
  - type: web
    name: social-media-backend
    runtime: docker
    plan: starter  # You can upgrade to standard/pro as needed
    region: oregon  # Choose your preferred region
    branch: main
    dockerfilePath: ./Dockerfile
    
    # Environment Variables
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      
      # Database Configuration (will be auto-populated by Render PostgreSQL)
      - key: DATABASE_URL
        fromDatabase:
          name: social-media-db
          property: connectionString
      
      - key: DB_USERNAME
        fromDatabase:
          name: social-media-db
          property: user
      
      - key: DB_PASSWORD
        fromDatabase:
          name: social-media-db
          property: password
      
      # Redis Configuration (will be auto-populated by Render Redis)
      - key: REDIS_URL
        fromService:
          name: social-media-redis
          type: redis
          property: connectionString
      
      # Note: All secrets below should be set manually in Render Dashboard
      # This keeps sensitive credentials out of your code repository
      
      # JWT Secret (Set in Dashboard - generate a strong 32+ character secret)
      # - key: JWT_SECRET
      #   value: [SET_IN_DASHBOARD]
      
      # Cloudinary Configuration (Set in Dashboard)
      # - key: CLOUDINARY_CLOUD_NAME
      #   value: [SET_IN_DASHBOARD]
      
      # - key: CLOUDINARY_API_KEY
      #   value: [SET_IN_DASHBOARD]
      
      # - key: CLOUDINARY_API_SECRET
      #   value: [SET_IN_DASHBOARD]
      
      # Email Configuration (Set in Dashboard)
      # - key: MAIL_USERNAME
      #   value: [SET_IN_DASHBOARD]
      
      # - key: MAIL_PASSWORD
      #   value: [SET_IN_DASHBOARD]
      
      # Application Base URL (will be auto-generated by Render)
      - key: APP_BASE_URL
        value: https://social-media-backend.onrender.com
    
    # Health Check
    healthCheckPath: /actuator/health
    
    # Build Command (if not using Dockerfile)
    # buildCommand: "./mvnw clean package -DskipTests"
    # startCommand: "java -jar target/*.jar"

# Database Service
databases:
  - name: social-media-db
    databaseName: socialmedia
    user: socialmedia_user
    plan: starter  # Free tier available
    region: oregon
    ipAllowList: []  # Empty means allow all (adjust for security)

# Redis Service  
services:
  - type: redis
    name: social-media-redis
    plan: starter  # Free tier available
    region: oregon
    ipAllowList: []